### ISSUE TITLE
Problem of Installation process on Windows

### ISSUE THREAD

**Issue by Anas-86** [badetitou/vscode-pharo#22]
Hallo, thanks for the valuable idea. I still however cannot get it run in windows. It would be very helpful for me and my colleagues (MS.c at Hagen university_Germany) if you could provide a video for the installation process.
We think we have followed the installation instructions literally, but we still do not get it run.

**Comment by badetitou** [comment]
Hello,

I'm running the project on my Windows computer, so it is possible :-) .
But I agree it is a good idea to have a video tutorial about installing it.
I'll do it and let you know quickly.

Cheers
Benoit

**Comment by badetitou** [comment]
Hello

The easiest way is to execute the command `Install the last version of the language server`, wait for installation, and restart. If you have any trouble, please, reopen the issue and detail how you tried to install the extension
