### ISSUE TITLE
Print and Show actions does not present the result.

### ISSUE THREAD

**Issue by jeffsantos** [badetitou/vscode-pharo#24]
Hi, I followed the steps to set up the vscode-pharo extension and Pharo Language Server. I downloaded a clean Pharo 10 image and only install the Pharo Language Server v3. The connection between vscode and Pharo is ok. I can navigate the packages using the vscode proper view. Syntax highlight and code complete also worked perfectly. But when I try to show a result of a computation or print the result, nothing happens. A command to show results in Transcript worked fine, too. I tried to find any message reporting this situation on the web and in the Discord channel of Pharo, but I found nothing about.  Have you heard about this situation? Any tip to solve?

**Comment by akevalion** [comment]
Hello I have in the same situation
I have tried with @badetitou 
```st
self inform: 'Hello World'
```
It works, but sometimes does not work

**Comment by badetitou** [comment]
I just [release a version of Pharo-LanguageServer](https://github.com/badetitou/Pharo-LanguageServer/releases/tag/v3.1.2) with the fix
I released a version of vscode-pharo that will use the language server with the fixed install (I hope it will be accepted by the platform)

You have to execute the command pharo:installIt to be sure to get the last version 

![image](https://user-images.githubusercontent.com/6225039/224315882-687e9c98-5c9d-4883-80a5-993b149181e4.png)


I'm trying to add more and more tests to the Pharo-LanguageServer project, sorry for the problems :-)

**Comment by badetitou** [comment]
Please, check that you have version 2.1.6 of the extension and retry. If the error persists, you can reopen the issue

**Comment by badetitou** [comment]
Seems to still have the bug (at least on osX)

**Comment by jeffsantos** [comment]
Hello @badetitou! Thank you for your work. To give you some feedback: I installed the latest version using the `pharo:installIt` command (actually, this version returned 2.1.7). I tried this latest version on Windows 11 and macOS Monterey. In both I got the same behavior: printing is now working fine, but the show command is not returning anything.

**Comment by badetitou** [comment]
Thx for the feedback. I'll check for the "showCommand". 
I expect it to display the result in a popUp in VSCode

**Comment by badetitou** [comment]
should be fix in v2.1.8

**Comment by jeffsantos** [comment]
I got the 2.1.8. It's working perfectly now. Thank you again.
