### ISSUE TITLE
5 factorial does not work

### ISSUE THREAD

**Issue by akevalion** [badetitou/vscode-pharo#25]
I have tried to use it to print the result of

<img width="614" alt="image" src="https://user-images.githubusercontent.com/10532890/221566528-fa8b71c1-5193-4514-a99d-26d5c0456f19.png">

please note that `self inform: 5 factorial asString` works.

**Comment by badetitou** [comment]
I got it working with version 2.1.6 of the extension and the last Pharo-LanguageServer.
Please try again with this version and reopens with the error persist

> I just released version 2.1.6, so it can take a bit of time before Microsoft says to you you can update

**Comment by badetitou** [comment]
Based on comments in https://github.com/badetitou/vscode-pharo/issues/24
I think this issue is solved now
