### ISSUE TITLE
Install command not work properly in macOs

### ISSUE THREAD

**Issue by akevalion** [badetitou/vscode-pharo#26]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/10532890/224323436-aa4940c8-1231-4926-94a0-cd59803dcae0.png">

because in macOs you have to consider the path `your/path/to/Pharo.app/Contents/MacOS/Pharo`
Then the install command should set the correct path in macOs or linux or windows

**Comment by badetitou** [comment]
I made this modification in the code
https://github.com/badetitou/vscode-pharo/commit/cff7722d5cf57aa419c17e560956fcead290cb81#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626

The release is rolling out for testing on mac computer

**Comment by badetitou** [comment]
Seems to work now
https://github.com/badetitou/vscode-pharo/issues/24#issuecomment-1464933148
