### ISSUE TITLE
run pharo headless

### ISSUE THREAD

**Issue by akevalion** [badetitou/vscode-pharo#28]
When the VSCode runs a st file it opens a new pharo moose image. is it possible to run this image in headless mode?

`./pharo --headless Pharo.image `

**Comment by badetitou** [comment]
You have in the options a way to run it headless.

![image](https://user-images.githubusercontent.com/6225039/236199690-200471c1-94bf-4e5b-9ecc-407622e3328e.png)

The Debug does not work as well as I want. But the headless mode works on my linux and windows.
I suppose it also works on mac. If not I'll check it

**Comment by badetitou** [comment]
(I agree, it should be the default value. I though it was. I'll check that too for this PR)

**Comment by badetitou** [comment]
It is headless by default now 
https://github.com/badetitou/vscode-pharo/blob/main/package.json#L59
