### ISSUE TITLE
Format bug

### ISSUE THREAD

**Issue by scottming** [badetitou/vscode-pharo#3]
when I use format, the Chinese comment I write will be formatted into something I don't read.

**old: **

```
"
内部产品，即服务
"
Class {
	#name : #HcProduct,
	#superclass : #Object,
	#instVars : [
		'title',
		'services'
	],
	#category : #'HcSCRM-Core'
}
```

**new:**

```
 Class. "
���产�������
"
{ 
	 #name.
	 :.
	 #HcProduct , #superclass.
	 :.
	 #Object , #instVars.
	 :.
	 [ 'title' , 'services' ] , #category.
	 :.
	#'HcSCRM-Core' }
```

**Comment by badetitou** [comment]
Hello

I think I achieve to fix the problem of encoding.
Can you check in your computer?

![image](https://user-images.githubusercontent.com/6225039/109036392-d640b100-76c9-11eb-97bb-452bef1bef79.png)

(you have to pull the last version of https://github.com/badetitou/Pharo-LanguageServer, if it works, I will release of new version)

**Comment by scottming** [comment]
Hello, @badetitou, I'm new to Pharo. Could you tell me how to modify this code for loading the main branch?

```
Metacello new
  githubUser: 'badetitou' project: 'Pharo-LanguageServer' commitish: 'v1.0.0' path: 'src';
  baseline: 'PharoLanguageServer';
  load
```

**Comment by badetitou** [comment]
You can replace `v1.0.0` by `main`

```st
​Metacello new
  githubUser: 'badetitou' project: 'Pharo-LanguageServer' commitish: 'main' path: 'src';
  baseline: 'PharoLanguageServer';
  load
```

**Comment by scottming** [comment]
![image](https://user-images.githubusercontent.com/12830256/109121864-c46f1480-7782-11eb-85a8-07eeb65ddf75.png)
It seems not work.

**Comment by badetitou** [comment]
Oh
Indeed, a method (auto-generated in my image -_-) was missing in the repository
I have pushed it (https://github.com/badetitou/Pharo-LanguageServer/commit/cb89289af8939488a50cdff1d0b5a1be76dc9edf)

can you pull the code again and try?

**Comment by scottming** [comment]
It seems not to work.

![image](https://user-images.githubusercontent.com/12830256/109246295-ed43e800-781c-11eb-93d3-afc292942e58.png)

I've updated the newest commit and reloaded the five packages.

![image](https://user-images.githubusercontent.com/12830256/109246321-0187e500-781d-11eb-995e-2658f9f0d1af.png)

**Comment by badetitou** [comment]
Can you give me the character you wrote?
So I can test

**Comment by scottming** [comment]
```st
"
行业分类，公司分类，供需分类等等
"
Class {
	#name : #HcCategory,
	#superclass : #Object,
	#instVars : [
		'name',
		'content'
	],
	#category : #'HcSCRM-Core'
}

{ #category : #accessing }
HcCategory >> content [
	^ content
]

{ #category : #accessing }
HcCategory >> content: anObject [
	content := anObject
]

{ #category : #accessing }
HcCategory >> name [
	^ name
]

{ #category : #accessing }
HcCategory >> name: anObject [
	name := anObject
]

```

**Comment by badetitou** [comment]
Ok, I find the bug. It is fixed now 😄 

![fixFormatTonel](https://user-images.githubusercontent.com/6225039/109267184-72bd9d00-7809-11eb-8e67-07eaf00f524d.gif)

**Comment by scottming** [comment]
Thanks for your work. It works.
