### ISSUE TITLE
Instance of RBVariableNode did not understand #selector

### ISSUE THREAD

**Issue by nachoba** [badetitou/vscode-pharo#7]
Hi, when trying some snippets in VSCode
![Capture2](https://user-images.githubusercontent.com/3520730/109086270-05671a80-76ea-11eb-825e-d118b7b2de43.PNG)
I get several of these
![Capture](https://user-images.githubusercontent.com/3520730/109086282-0c8e2880-76ea-11eb-9c1f-ca33b0c54fc6.PNG)

I'm using Pharo64-8.0-PLS (v1.0.3) image

**Comment by badetitou** [comment]
Hello, I have released today v1.0.4 with the fix for your bugs (it was ready weeks ago, but I forgot to release it)
